
---
# Describe the labels that once added to a pull request cause the app to assign
# randomly chosen reviewers.
labels:
  -
    # Define the groups of reviewers from which the reviewers will be chosen. In this
    # example, when the label `ready-for-review` is applied, two reviewers are
    # chosen from the first group and one reviewer from the second group.
    groups:
      -
        number_of_picks: 1
        possible_reviewers:
          - marianeum
          - Crunch09
          - jabeattie
    label: "ready for review"
  -
    groups:
      -
        number_of_picks: 1
        possible_reviewers:
          - foo
          - bar
          - baz
    label: "Ready for review - small"
# Optional: Define which Slack channel to notify once random reviewers have been
# chosen and their review was requested.
# The `URL` is of an [Incoming Webhook](https://api.slack.com/incoming-webhooks).
notifications:
  slack:
    url: "https://hooks.slack.com/services/AAA/BBB/CCC"
    channel: "#pull_requests"

# Optional: Define mappings between GitHub usernames and Slack usernames so people
# get a notification when their review is being requested.
# The slack user-id can be found in each user's profile settings.
user_mappings:
  florian:
    slack: U123456
  octobot:
    slack: U987654
