name: 'Find reviewers'
description: "Find random reviewers"
inputs:
  token:
    description: 'Github token'
    required: true
  type:
    description: 'Event that triggered this action'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
