on:
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  find_reviewers_job:
    runs-on: ubuntu-latest
    name: A job to pick reviewers
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reviewers action step
        uses: ./
        id: find-reviewers
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          type: "${{ github.event_name }}"
